name: tic_tac_toe
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  # state management
  provider: ^6.0.5

  # local storage
  hive_flutter: ^1.1.0

  # create model easily
  json_annotation: ^4.8.1

  # language support
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

  # loading spinner package
  flutter_easyloading: ^3.0.5
  # responsive package
  flutter_screenutil: 5.9.3
  # svg image package
  flutter_svg: ^2.0.10+1
  firebase_core: ^2.24.2
  cloud_firestore: ^4.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.5
  flutter_lints: ^2.0.1
  json_serializable: ^6.7.0
  # Asset generation
  flutter_gen: ^5.4.0
  flutter_gen_runner:
  # native splash screen
  flutter_native_splash: ^2.4.0
  # app icon
  flutter_launcher_icons: ^0.13.1
  # cache model generator
  hive_generator: ^2.0.1
  # package name change
  package_rename: ^1.7.1




flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/
    - assets/images/

flutter_gen:
  output: lib/src/core/assets_gen/
  line_length: 80

  integrations:
    flutter_svg: true
    lottie: true
    # flare_flutter: true
    # rive: true


flutter_native_splash:
  color: "#D93B6A"
  image: "assets/images/app_logo.png"
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: center
  fullscreen: true

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/app_logo.png"
  min_sdk_android: 21
  remove_alpha_ios: true

package_rename_config:
  android:
    app_name: Tic Tac Toe
    package_name: com.tictac.toe
    override_old_package: com.example.tic_tac_toe
  ios:
    app_name: Tic Tac Toe
    bundle_name: Tic Tac Toe
    package_name: com.tictac.toe



